Seed admin to database
NexaScaleHQ/travel-app-project pull request #28
Opened 2023-08-07 12:57 UTC by Japheth-Joepari

Seeded admin to database: created the AdminSeeder file in seeders directory with the required fields and called the AdminSeeder::class in the databaseSeeder.php file in the seeders directory.

2023-08-07 15:48 UTC, davydocsurg requested changes

2023-08-07 15:48 UTC, davydocsurg commented on database/seeders/AdminSeeder.php
> +            // 'confirm_password' => Hash::make('password'), //confirm_password column does does not exist
Please, remove the comments

2023-08-07 15:48 UTC, davydocsurg commented on database/seeders/DatabaseSeeder.php
>          //     'name' => 'Test User',
Remove the comments here too

2023-08-07 23:11 UTC, Japheth-Joepari commented on database/seeders/AdminSeeder.php
> +            // 'confirm_password' => Hash::make('password'), //confirm_password column does does not exist
Done.

2023-08-07 23:11 UTC, Japheth-Joepari commented on database/seeders/DatabaseSeeder.php
>          //     'name' => 'Test User',
Done.

2023-08-08 08:11 UTC, davydocsurg approved these changes

2023-08-08 08:11 UTC, merged