Created restaurant table and model
NexaScaleHQ/travel-app-project pull request #59
Opened 2023-09-17 23:04 UTC by Danie-O

2023-09-19 17:07 UTC, davydocsurg requested changes

2023-09-19 17:07 UTC, davydocsurg commented on app/Models/Image.php
> +    public function imageable() {
Please make sure that you only include modifications that pertain to a specific ticket.

2023-09-19 18:17 UTC, Danie-O commented on app/Models/Image.php
> +    public function imageable() {
Well noted. 
I have reverted the changes relating to the Users-Images relationship and the deletion of the User.php file

2023-09-21 09:29 UTC, davydocsurg approved these changes

2023-09-21 09:29 UTC, merged